allowBuilds:
  "@deepseek-ai/dsh-subprocess-local": true
  "@google/genai": true
  koffi: true
  node-pty: true
  protobufjs: true
  electron: true
  electron-builder: true
  electron-winstaller: true
overrides:
  "@electron/get": "3.1.0"
